const coreA1 = {
  id: 'core-a1',
  name: 'Core A1 — Essentials',
  cards: [
    // --- Greetings & small talk ---
    { id: '1', lt: 'Labas', en: 'Hello', ru: 'Привет', topic: 'greetings' },
    { id: 'core-101', lt: 'Sveiki', en: 'Hello (formal/pl.)', ru: 'Здравствуйте', topic: 'greetings' },
    { id: 'core-102', lt: 'Laba diena', en: 'Good afternoon / Hello', ru: 'Добрый день', topic: 'greetings' },
    { id: 'core-103', lt: 'Labas rytas', en: 'Good morning', ru: 'Доброе утро', topic: 'greetings' },
    { id: 'core-104', lt: 'Labas vakaras', en: 'Good evening', ru: 'Добрый вечер', topic: 'greetings' },
    { id: 'core-105', lt: 'Viso gero', en: 'Goodbye', ru: 'До свидания', topic: 'greetings' },
    { id: 'core-106', lt: 'Iki', en: 'See you / Bye', ru: 'Пока / До встречи', topic: 'greetings' },
    { id: 'core-107', lt: 'Iki pasimatymo', en: 'See you later', ru: 'До встречи', topic: 'greetings' },
    { id: 'core-108', lt: 'Malonu susipažinti', en: 'Nice to meet you', ru: 'Приятно познакомиться', topic: 'greetings' },
    { id: 'core-109', lt: 'Kaip sekasi?', en: 'How are you?', ru: 'Как дела?', topic: 'greetings' },
    { id: 'core-110', lt: 'Gerai', en: 'Good / Fine', ru: 'Хорошо', topic: 'greetings' },
    { id: 'core-111', lt: 'Blogai', en: 'Bad', ru: 'Плохо', topic: 'greetings' },
    { id: '2', lt: 'Ačiū', en: 'Thank you', ru: 'Спасибо', topic: 'greetings' },
    { id: 'core-112', lt: 'Ačiū labai', en: 'Thank you very much', ru: 'Большое спасибо', topic: 'greetings' },
    { id: '3', lt: 'Prašom', en: "Please / You're welcome", ru: 'Пожалуйста', topic: 'greetings' },
    { id: 'core-113', lt: 'Prašau', en: 'Please (I ask) / You\'re welcome', ru: 'Пожалуйста', topic: 'greetings' },
    { id: '4', lt: 'Atsiprašau', en: 'Sorry / Excuse me', ru: 'Извините', topic: 'greetings' },

    // --- Core yes/no & quick replies ---
    { id: '5', lt: 'Taip', en: 'Yes', ru: 'Да', topic: 'core' },
    { id: '6', lt: 'Ne', en: 'No', ru: 'Нет', topic: 'core' },
    { id: 'core-114', lt: 'Galbūt', en: 'Maybe', ru: 'Возможно', topic: 'core' },
    { id: 'core-115', lt: 'Žinoma', en: 'Of course', ru: 'Конечно', topic: 'core' },
    { id: 'core-116', lt: 'Tikrai', en: 'Really / For sure', ru: 'Точно / Правда', topic: 'core' },

    // --- Survival classroom / conversation ---
    { id: 'core-117', lt: 'Gal galite padėti?', en: 'Could you help?', ru: 'Не могли бы вы помочь?', topic: 'core' },
    { id: 'core-118', lt: 'Gal galite pakartoti?', en: 'Could you repeat?', ru: 'Не могли бы вы повторить?', topic: 'core' },
    { id: 'core-119', lt: 'Kalbėkite lėčiau, prašau', en: 'Speak more slowly, please', ru: 'Говорите, пожалуйста, медленнее', topic: 'core' },
    { id: 'core-120', lt: 'Aš nekalbu lietuviškai', en: "I don't speak Lithuanian", ru: 'Я не говорю по‑литовски', topic: 'core' },
    { id: 'core-121', lt: 'Aš truputį kalbu lietuviškai', en: 'I speak a little Lithuanian', ru: 'Я немного говорю по‑литовски', topic: 'core' },
    { id: 'core-122', lt: 'Ar kalbate angliškai?', en: 'Do you speak English?', ru: 'Вы говорите по‑английски?', topic: 'core' },
    { id: 'core-123', lt: 'Aš mokausi lietuvių kalbos', en: "I'm learning Lithuanian", ru: 'Я учу литовский язык', topic: 'core' },

    // --- Basic questions ---
    { id: 'core-124', lt: 'Kas?', en: 'Who?', ru: 'Кто?', topic: 'questions' },
    { id: 'core-125', lt: 'Ką?', en: 'What? (acc.)', ru: 'Что?', topic: 'questions' },
    { id: 'core-126', lt: 'Kur?', en: 'Where?', ru: 'Где?', topic: 'questions' },
    { id: 'core-127', lt: 'Kaip?', en: 'How?', ru: 'Как?', topic: 'questions' },
    { id: 'core-128', lt: 'Kada?', en: 'When?', ru: 'Когда?', topic: 'questions' },
    { id: 'core-129', lt: 'Kodėl?', en: 'Why?', ru: 'Почему?', topic: 'questions' },
    { id: 'core-130', lt: 'Kiek?', en: 'How much / How many?', ru: 'Сколько?', topic: 'questions' },
    { id: 'core-131', lt: 'Kur yra ...?', en: 'Where is ...?', ru: 'Где находится …?', topic: 'questions' },
    { id: 'core-132', lt: 'Kas tai?', en: 'What is this?', ru: 'Что это?', topic: 'questions' },

    // --- Pronouns & possessives ---
    { id: 'core-133', lt: 'Aš', en: 'I', ru: 'Я', topic: 'pronouns' },
    { id: '10', lt: 'Tu esi', en: 'You are', ru: 'Ты', topic: 'core' },
    { id: 'core-134', lt: 'Tu', en: 'You (sg.)', ru: 'Ты', topic: 'pronouns' },
    { id: 'core-135', lt: 'Jūs', en: 'You (pl./formal)', ru: 'Вы', topic: 'pronouns' },
    { id: 'core-136', lt: 'Jis', en: 'He', ru: 'Он', topic: 'pronouns' },
    { id: 'core-137', lt: 'Ji', en: 'She', ru: 'Она', topic: 'pronouns' },
    { id: 'core-138', lt: 'Mes', en: 'We', ru: 'Мы', topic: 'pronouns' },
    { id: 'core-139', lt: 'Jie', en: 'They (masc.)', ru: 'Они (м.)', topic: 'pronouns' },
    { id: 'core-140', lt: 'Jos', en: 'They (fem.)', ru: 'Они (ж.)', topic: 'pronouns' },
    { id: 'core-141', lt: 'Mano', en: 'My', ru: 'Мой/моя/моё', topic: 'pronouns' },
    { id: 'core-142', lt: 'Tavo', en: 'Your (sg.)', ru: 'Твой/твоя/твоё', topic: 'pronouns' },
    { id: 'core-143', lt: 'Jūsų', en: 'Your (pl./formal)', ru: 'Ваш/ваша/ваше', topic: 'pronouns' },
    { id: 'core-144', lt: 'Jo', en: 'His', ru: 'Его', topic: 'pronouns' },
    { id: 'core-145', lt: 'Jos', en: 'Her', ru: 'Её', topic: 'pronouns' },
    { id: 'core-146', lt: 'Mūsų', en: 'Our', ru: 'Наш/наша/наше', topic: 'pronouns' },
    { id: 'core-147', lt: 'Jų', en: 'Their', ru: 'Их', topic: 'pronouns' },

    // --- Numbers (0–20) ---
    { id: 'core-148', lt: 'Nulis', en: 'Zero', ru: 'Ноль', topic: 'numbers' },
    { id: '14', lt: 'Vienas / viena', en: 'One (m/f)', ru: 'Один / одна', topic: 'numbers' },
    { id: '15', lt: 'Du / dvi', en: 'Two (m/f)', ru: 'Два / две', topic: 'numbers' },
    { id: '16', lt: 'Trys', en: 'Three', ru: 'Три', topic: 'numbers' },
    { id: 'core-149', lt: 'Keturi', en: 'Four', ru: 'Четыре', topic: 'numbers' },
    { id: 'core-150', lt: 'Penki', en: 'Five', ru: 'Пять', topic: 'numbers' },
    { id: 'core-151', lt: 'Šeši', en: 'Six', ru: 'Шесть', topic: 'numbers' },
    { id: 'core-152', lt: 'Septyni', en: 'Seven', ru: 'Семь', topic: 'numbers' },
    { id: 'core-153', lt: 'Aštuoni', en: 'Eight', ru: 'Восемь', topic: 'numbers' },
    { id: 'core-154', lt: 'Devyni', en: 'Nine', ru: 'Девять', topic: 'numbers' },
    { id: 'core-155', lt: 'Dešimt', en: 'Ten', ru: 'Десять', topic: 'numbers' },
    { id: 'core-156', lt: 'Vienuolika', en: 'Eleven', ru: 'Одиннадцать', topic: 'numbers' },
    { id: 'core-157', lt: 'Dvylika', en: 'Twelve', ru: 'Двенадцать', topic: 'numbers' },
    { id: 'core-158', lt: 'Trylika', en: 'Thirteen', ru: 'Тринадцать', topic: 'numbers' },
    { id: 'core-159', lt: 'Keturiolika', en: 'Fourteen', ru: 'Четырнадцать', topic: 'numbers' },
    { id: 'core-160', lt: 'Penkiolika', en: 'Fifteen', ru: 'Пятнадцать', topic: 'numbers' },
    { id: 'core-161', lt: 'Šešiolika', en: 'Sixteen', ru: 'Шестнадцать', topic: 'numbers' },
    { id: 'core-162', lt: 'Septyniolika', en: 'Seventeen', ru: 'Семнадцать', topic: 'numbers' },
    { id: 'core-163', lt: 'Aštuoniolika', en: 'Eighteen', ru: 'Восемнадцать', topic: 'numbers' },
    { id: 'core-164', lt: 'Devyniolika', en: 'Nineteen', ru: 'Девятнадцать', topic: 'numbers' },
    { id: 'core-165', lt: 'Dvidešimt', en: 'Twenty', ru: 'Двадцать', topic: 'numbers' },

    // --- Time / days ---
    { id: '31', lt: 'Šiandien', en: 'Today', ru: 'Сегодня', topic: 'time' },
    { id: '32', lt: 'Rytoj', en: 'Tomorrow', ru: 'Завтра', topic: 'time' },
    { id: '33', lt: 'Vakar', en: 'Yesterday', ru: 'Вчера', topic: 'time' },
    { id: 'core-166', lt: 'Rytas', en: 'Morning', ru: 'Утро', topic: 'time' },
    { id: 'core-167', lt: 'Vakaras', en: 'Evening', ru: 'Вечер', topic: 'time' },
    { id: 'core-168', lt: 'Dabar', en: 'Now', ru: 'Сейчас', topic: 'time' },
    { id: 'core-169', lt: 'Vėliau', en: 'Later', ru: 'Позже', topic: 'time' },
    { id: 'core-170', lt: 'Anksti', en: 'Early', ru: 'Рано', topic: 'time' },
    { id: 'core-171', lt: 'Vėlai', en: 'Late', ru: 'Поздно', topic: 'time' },
    { id: 'core-172', lt: 'Pirmadienis', en: 'Monday', ru: 'Понедельник', topic: 'time' },
    { id: 'core-173', lt: 'Antradienis', en: 'Tuesday', ru: 'Вторник', topic: 'time' },
    { id: 'core-174', lt: 'Trečiadienis', en: 'Wednesday', ru: 'Среда', topic: 'time' },
    { id: 'core-175', lt: 'Ketvirtadienis', en: 'Thursday', ru: 'Четверг', topic: 'time' },
    { id: 'core-176', lt: 'Penktadienis', en: 'Friday', ru: 'Пятница', topic: 'time' },
    { id: 'core-177', lt: 'Šeštadienis', en: 'Saturday', ru: 'Суббота', topic: 'time' },
    { id: 'core-178', lt: 'Sekmadienis', en: 'Sunday', ru: 'Воскресенье', topic: 'time' },

    // --- Directions & place words ---
    { id: 'core-179', lt: 'Kairė', en: 'Left', ru: 'Лево', topic: 'directions' },
    { id: 'core-180', lt: 'Dešinė', en: 'Right', ru: 'Право', topic: 'directions' },
    { id: 'core-181', lt: 'Tiesiai', en: 'Straight ahead', ru: 'Прямо', topic: 'directions' },
    { id: 'core-182', lt: 'Čia', en: 'Here', ru: 'Здесь', topic: 'directions' },
    { id: 'core-183', lt: 'Ten', en: 'There', ru: 'Там', topic: 'directions' },
    { id: 'core-184', lt: 'Netoli', en: 'Nearby / Not far', ru: 'Недалеко', topic: 'directions' },
    { id: 'core-185', lt: 'Toli', en: 'Far', ru: 'Далеко', topic: 'directions' },
    { id: 'core-186', lt: 'Atidaryta', en: 'Open', ru: 'Открыто', topic: 'directions' },
    { id: 'core-187', lt: 'Uždaryta', en: 'Closed', ru: 'Закрыто', topic: 'directions' },

    // --- Travel & services ---
    { id: 'core-188', lt: 'Traukinys', en: 'Train', ru: 'Поезд', topic: 'travel' },
    { id: 'core-189', lt: 'Autobusas', en: 'Bus', ru: 'Автобус', topic: 'travel' },
    { id: 'core-190', lt: 'Taksi', en: 'Taxi', ru: 'Такси', topic: 'travel' },
    { id: 'core-191', lt: 'Oro uostas', en: 'Airport', ru: 'Аэропорт', topic: 'travel' },
    { id: 'core-192', lt: 'Viešbutis', en: 'Hotel', ru: 'Отель', topic: 'travel' },
    { id: 'core-193', lt: 'Kambarys', en: 'Room', ru: 'Комната / номер', topic: 'travel' },
    { id: 'core-194', lt: 'Rezervacija', en: 'Reservation', ru: 'Бронирование', topic: 'travel' },
    { id: 'core-195', lt: 'Policija', en: 'Police', ru: 'Полиция', topic: 'travel' },
    { id: 'core-196', lt: 'Vaistinė', en: 'Pharmacy', ru: 'Аптека', topic: 'travel' },
    { id: 'core-197', lt: 'Ligoninė', en: 'Hospital', ru: 'Больница', topic: 'travel' },

    // --- Food & ordering basics ---
    { id: '7', lt: 'Vanduo', en: 'Water', ru: 'Вода', topic: 'food' },
    { id: '8', lt: 'Kava', en: 'Coffee', ru: 'Кофе', topic: 'food' },
    { id: 'core-198', lt: 'Meniu', en: 'Menu', ru: 'Меню', topic: 'food' },
    { id: 'core-199', lt: 'Sąskaita', en: 'The bill / receipt', ru: 'Счёт', topic: 'food' },
    { id: 'core-200', lt: 'Skanaus!', en: 'Enjoy your meal!', ru: 'Приятного аппетита!', topic: 'food' },
    { id: 'core-201', lt: 'Skanu', en: 'Tasty / Delicious', ru: 'Вкусно', topic: 'food' },
    { id: 'core-202', lt: 'Neskanu', en: 'Not tasty', ru: 'Невкусно', topic: 'food' },
    { id: 'core-203', lt: 'Su …', en: 'With …', ru: 'С …', topic: 'food' },
    { id: 'core-204', lt: 'Be …', en: 'Without …', ru: 'Без …', topic: 'food' },
    { id: 'core-205', lt: 'Vieną …, prašau', en: 'One …, please', ru: 'Одну …, пожалуйста', topic: 'food' },

    // --- Money & shopping ---
    { id: '12', lt: 'Kiek tai kainuoja?', en: 'How much is it?', ru: 'Сколько стоит?', topic: 'shopping' },
    { id: 'core-206', lt: 'Brangu', en: 'Expensive', ru: 'Дорого', topic: 'shopping' },
    { id: 'core-207', lt: 'Pigu', en: 'Cheap', ru: 'Дёшево', topic: 'shopping' },
    { id: 'core-208', lt: 'Nuolaida', en: 'Discount', ru: 'Скидка', topic: 'shopping' },
    { id: 'core-209', lt: 'Ar galite padaryti nuolaidą?', en: 'Can you make a discount?', ru: 'Можно скидку?', topic: 'shopping' },
    { id: 'core-210', lt: 'Kortele', en: 'By card', ru: 'Картой', topic: 'shopping' },
    { id: 'core-211', lt: 'Grynais', en: 'In cash', ru: 'Наличными', topic: 'shopping' },
    { id: 'core-212', lt: 'Čekis', en: 'Receipt', ru: 'Чек', topic: 'shopping' },

    // --- Emergencies & health ---
    { id: 'core-213', lt: 'Padėkite!', en: 'Help!', ru: 'Помогите!', topic: 'emergency' },
    { id: 'core-214', lt: 'Skubi pagalba', en: 'Emergency (service)', ru: 'Скорая помощь', topic: 'emergency' },
    { id: 'core-215', lt: 'Pavojus', en: 'Danger', ru: 'Опасность', topic: 'emergency' },
    { id: 'core-216', lt: 'Aš pasiklydau', en: 'I am lost', ru: 'Я заблудился/ась', topic: 'emergency' },
    { id: 'core-217', lt: 'Gydytojas', en: 'Doctor', ru: 'Врач', topic: 'health' },
    { id: 'core-218', lt: 'Vaistai', en: 'Medicine', ru: 'Лекарства', topic: 'health' },
    { id: 'core-219', lt: 'Alergija', en: 'Allergy', ru: 'Аллергия', topic: 'health' },
    { id: 'core-220', lt: 'Esu alergiškas / alergiška …', en: 'I am allergic to … (m/f)', ru: 'У меня аллергия на …', topic: 'health' },

    // --- Basic verbs & patterns ---
    { id: '9', lt: 'Aš esu', en: 'I am', ru: 'Я', topic: 'core' },
    { id: '17', lt: 'Aš noriu', en: 'I want', ru: 'Я хочу', topic: 'core' },
    { id: '18', lt: 'Aš suprantu', en: 'I understand', ru: 'Я понимаю', topic: 'core' },
    { id: '19', lt: 'Nesuprantu', en: "I don't understand", ru: 'Я не понимаю', topic: 'core' },
    { id: 'core-221', lt: 'Aš žinau', en: 'I know', ru: 'Я знаю', topic: 'verbs' },
    { id: 'core-222', lt: 'Aš nežinau', en: 'I don\'t know', ru: 'Я не знаю', topic: 'verbs' },
    { id: 'core-223', lt: 'Supratau', en: 'Got it / I understood', ru: 'Понял(а)', topic: 'verbs' },
    { id: 'core-224', lt: 'Man reikia …', en: 'I need …', ru: 'Мне нужно …', topic: 'verbs' },
    { id: 'core-225', lt: 'Aš galiu', en: 'I can', ru: 'Я могу', topic: 'verbs' },
    { id: 'core-226', lt: 'Ar galiu …?', en: 'May I …?', ru: 'Можно мне …?', topic: 'verbs' },
    { id: 'core-227', lt: 'Man patinka', en: 'I like', ru: 'Мне нравится', topic: 'verbs' },
    { id: 'core-228', lt: 'Man nepatinka', en: "I don't like", ru: 'Мне не нравится', topic: 'verbs' },
    { id: 'core-229', lt: 'Turiu', en: 'I have', ru: 'У меня есть', topic: 'verbs' },
    { id: 'core-230', lt: 'Neturiu', en: "I don't have", ru: 'У меня нет', topic: 'verbs' },

    // --- Weather ---
    { id: 'core-231', lt: 'Oras', en: 'Weather', ru: 'Погода', topic: 'weather' },
    { id: 'core-232', lt: 'Šilta', en: 'Warm', ru: 'Тепло', topic: 'weather' },
    { id: 'core-233', lt: 'Šalta', en: 'Cold', ru: 'Холодно', topic: 'weather' },
    { id: 'core-234', lt: 'Karšta', en: 'Hot', ru: 'Жарко', topic: 'weather' },
    { id: 'core-235', lt: 'Lyja', en: 'It is raining', ru: 'Идёт дождь', topic: 'weather' },
    { id: 'core-236', lt: 'Sninga', en: 'It is snowing', ru: 'Идёт снег', topic: 'weather' },

    // --- Colors ---
    { id: 'core-237', lt: 'Balta', en: 'White', ru: 'Белый/ая', topic: 'colors' },
    { id: 'core-238', lt: 'Juoda', en: 'Black', ru: 'Чёрный/ая', topic: 'colors' },
    { id: 'core-239', lt: 'Raudona', en: 'Red', ru: 'Красный/ая', topic: 'colors' },
    { id: 'core-240', lt: 'Mėlyna', en: 'Blue', ru: 'Синий/ая', topic: 'colors' },
    { id: 'core-241', lt: 'Žalia', en: 'Green', ru: 'Зелёный/ая', topic: 'colors' },
    { id: 'core-242', lt: 'Geltona', en: 'Yellow', ru: 'Жёлтый/ая', topic: 'colors' },

    // --- Basic adjectives ---
    { id: 'core-243', lt: 'Geras', en: 'Good', ru: 'Хороший', topic: 'adjectives' },
    { id: 'core-244', lt: 'Blogas', en: 'Bad', ru: 'Плохой', topic: 'adjectives' },
    { id: 'core-245', lt: 'Didelis', en: 'Big', ru: 'Большой', topic: 'adjectives' },
    { id: 'core-246', lt: 'Mažas', en: 'Small', ru: 'Маленький', topic: 'adjectives' },
    { id: 'core-247', lt: 'Gražus', en: 'Beautiful / Nice', ru: 'Красивый', topic: 'adjectives' },
    { id: 'core-248', lt: 'Naujas', en: 'New', ru: 'Новый', topic: 'adjectives' },
    { id: 'core-249', lt: 'Senas', en: 'Old', ru: 'Старый', topic: 'adjectives' },
    { id: 'core-250', lt: 'Greitas', en: 'Fast', ru: 'Быстрый', topic: 'adjectives' },
    { id: 'core-251', lt: 'Lėtas', en: 'Slow', ru: 'Медленный', topic: 'adjectives' },

    // --- Identity & introductions ---
    { id: 'core-252', lt: 'Mano vardas …', en: 'My name is …', ru: 'Меня зовут …', topic: 'identity' },
    { id: 'core-253', lt: 'Koks tavo vardas?', en: 'What is your name? (sg.)', ru: 'Как тебя зовут?', topic: 'identity' },
    { id: 'core-254', lt: 'Iš kur tu esi?', en: 'Where are you from?', ru: 'Ты откуда?', topic: 'identity' },
    { id: 'core-255', lt: 'Aš esu iš …', en: 'I am from …', ru: 'Я из …', topic: 'identity' },
    { id: 'core-256', lt: 'Kiek tau metų?', en: 'How old are you?', ru: 'Сколько тебе лет?', topic: 'identity' },
    { id: 'core-257', lt: 'Man … metų', en: 'I am … years old', ru: 'Мне … лет', topic: 'identity' },

    // --- Navigation / misc ---
    { id: 'core-258', lt: 'Adresas', en: 'Address', ru: 'Адрес', topic: 'navigation' },
    { id: 'core-259', lt: 'Žemėlapis', en: 'Map', ru: 'Карта', topic: 'navigation' },
    { id: 'core-260', lt: 'Telefonas', en: 'Phone', ru: 'Телефон', topic: 'navigation' },
    { id: '11', lt: 'Kur tualetas?', en: 'Where is the toilet?', ru: 'Где туалет?', topic: 'travel' },
    { id: 'core-261', lt: 'Tualetas', en: 'Toilet', ru: 'Туалет', topic: 'navigation' },

    // --- From earlier core deck ---
    { id: '13', lt: 'Aš gyvenu Vilniuje', en: 'I live in Vilnius', ru: 'Я живу в Вильнюсе', topic: 'life' },
    { id: '20', lt: 'Lietuvių kalba', en: 'Lithuanian language', ru: 'Литовский язык', topic: 'meta' },
  ],
};
export default coreA1;
